src/Entity/Adherent.php
<?php

namespace App\Entity;

use App\Repository\AdherentRepository;
use App\Enum\Niveau;
use App\Enum\RoleAdherent;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: AdherentRepository::class)]
class Adherent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column(length: 50)]
    private ?string $mot_de_passe = null;

    #[ORM\Column(type: 'date')]
    private ?\DateTime $date_de_naissance = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTime $date_inscription = null;

    #[ORM\Column(length: 20)]
    private ?string $numero_licence = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTime $date_expiration_licence = null;

    #[ORM\Column(enumType: RoleAdherent::class)]
    private ?RoleAdherent $roleAdherent;

    #[ORM\Column(enumType: Niveau::class)]
    private ?Niveau $niveau = null;




    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->mot_de_passe;
    }

    public function setMotDePasse(string $mot_de_passe): static
    {
        $this->mot_de_passe = $mot_de_passe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTime
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTime $date_de_naissance): static
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getDateInscription(): ?\DateTime
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTime $date_inscription): static
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    public function getNumeroLicence(): ?string
    {
        return $this->numero_licence;
    }

    public function setNumeroLicence(string $numero_licence): static
    {
        $this->numero_licence = $numero_licence;

        return $this;
    }

    public function getDateExpirationLicence(): ?\DateTime
    {
        return $this->date_expiration_licence;
    }

    public function setDateExpirationLicence(\DateTime $date_expiration_licence): static
    {
        $this->date_expiration_licence = $date_expiration_licence;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getNiveau(): ?Niveau
    {
        return $this->niveau;
    }

    public function setNiveau(?Niveau $niveau): static
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getRoleAdherent(): ?RoleAdherent
    {
        return $this->roleAdherent;
    }

    public function setRoleAdherent(RoleAdherent $roleAdherent): static
    {
        $this->roleAdherent = $roleAdherent;

        return $this;
    }

    // Méthode pour vérifier si l'adhérent est un administrateur licencié
    public function isAdministrateurLicencie(): bool
    {
        return $this->roleAdherent === RoleAdherent::ADMINISTRATEUR_LICENCIE;
    }
}

src/Entity/Adherents.php
<?php

namespace App\Entity;

use App\Repository\AdherentsRepository;
use App\Enum\Niveau;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: AdherentsRepository::class)]
class Adherents
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column(length: 50)]
    private ?string $mot_de_passe = null;

    #[ORM\Column(type: 'date')]
    private ?\DateTime $date_de_naissance = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTime $date_inscription = null;

    #[ORM\Column(length: 20)]
    private ?string $numero_licence = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTime $date_expiration_licence = null;

    #[ORM\Column(type: 'string', enumType: Niveau::class)]
    private ?Niveau $niveau = null;




    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->mot_de_passe;
    }

    public function setMotDePasse(string $mot_de_passe): static
    {
        $this->mot_de_passe = $mot_de_passe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTime
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTime $date_de_naissance): static
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getDateInscription(): ?\DateTime
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTime $date_inscription): static
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    public function getNumeroLicence(): ?string
    {
        return $this->numero_licence;
    }

    public function setNumeroLicence(string $numero_licence): static
    {
        $this->numero_licence = $numero_licence;

        return $this;
    }

    public function getDateExpirationLicence(): ?\DateTime
    {
        return $this->date_expiration_licence;
    }

    public function setDateExpirationLicence(\DateTime $date_expiration_licence): static
    {
        $this->date_expiration_licence = $date_expiration_licence;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getNiveau(): ?Niveau
    {
        return $this->niveau;
    }

    public function setNiveau(?Niveau $niveau): static
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }
}

src/Form/AdherentType.php
<?php

namespace App\Form;

use App\Entity\Adherent;
use App\Enum\Niveau;
use App\Enum\RoleAdherent;
use App\Form\Transformer\RoleAdherentTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdherentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class)
            ->add('prenom', TextType::class)
            ->add('adresse', TextType::class)
            ->add('telephone', TextType::class, ['required' => false])
            ->add('photo', FileType::class, ['required' => false])
            ->add('email', EmailType::class)
            ->add('mot_de_passe', PasswordType::class)
            ->add(
                'date_de_naissance',
                DateType::class,
                ['widget' => 'single_text'],
                null
            )
            ->add('date_inscription', null, [
                'widget' => 'single_text',
            ])
            ->add('numero_licence', TextType::class)
            ->add('date_expiration_licence', DateType::class, ['widget' => 'single_text'], null)
            ->add(
                'niveau',
                ChoiceType::class,
                [
                    'choices' => [
                        'Débutant' => Niveau::DEBUTANT,
                        'Loisir' => Niveau::LOISIR,
                        'Avancé' => Niveau::AVANCE,
                    ],
                ]
            )
            ->add('roleAdherent', ChoiceType::class, [
                'choices' => [
                    'Licencié' => RoleAdherent::LICENCIE->value,
                    'Administrateur_Licencié' => RoleAdherent::ADMINISTRATEUR_LICENCIE->value,
                ],
                'expanded' => true,  // Affichage sous forme de boutons radio
                'multiple' => false, // Un seul choix possible
            ])
            ->get('roleAdherent')
            ->addModelTransformer(new RoleAdherentTransformer()) // Ajouter le transformateur
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Adherent::class,
        ]);
    }
}

src/Controller/AdherentController.php
<?php

namespace App\Controller;


use App\Entity\Adherent;
use App\Form\AdherentType;
use App\Repository\AdherentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class AdherentController extends AbstractController
{
    #[Route('/adherent', name: 'app_adherent')]
    public function index(AdherentRepository $adherentRepository): Response
    {
        $adherents = $adherentRepository->findAll();
        return $this->render('adherent/index.html.twig', [
            'adherents' => $adherents,
        ]);
    }

    // Afficher un adhérent spécifique
    #[Route('/adherent/{id}', name: 'adherent_show')]
    public function show(Adherent $adherent): Response
    {
        return $this->render('adherent/show.html.twig', [
            'adherent' => $adherent,
        ]);
    }

    // Inscription d'un nouvel adhérent
    #[Route('/inscription/adherent', name: 'inscription_adherent')]
    public function create(Request $request, EntityManagerInterface $entityManager): Response
    {
        $adherent = new Adherent();
        $form = $this->createForm(AdherentType::class, $adherent); // Formulaire d'inscription

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $adherent->setDateInscription(new \DateTime());
            $adherent->setDateExpirationLicence(new \DateTime('+1 year')); // Licence valable 1 an à partir de la date d'inscription
            $entityManager->persist($adherent);
            $entityManager->flush();

            foreach ($form->getErrors(true) as $error) {
                dump($error->getMessage());
            }

            // Message de succès et redirection vers la liste des adhérents
            $this->addFlash('success', 'Inscription effectuée avec succès!');
            return $this->redirectToRoute('app_adherent');
        }

        return $this->render('adherent/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    // Créer un nouvel adhérent
    // #[Route('/adherent/new', name: 'adherent_create')]
    // public function create(Request $request, EntityManagerInterface $entityManager): Response
    // {
    //     $adherent = new Adherent();
    //     $form = $this->createForm(AdherentType::class, $adherent); // Formulaire de création

    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $adherent->setDateInscription(new \DateTime()); // La date d'inscription est la date actuelle
    //         $adherent->setDateExpirationLicence(new \DateTime('+1 year')); // Exemple : licence valable 1 an
    //         $entityManager->persist($adherent);
    //         $entityManager->flush();

    //         // Message de succès et redirection vers la liste des adhérents
    //         $this->addFlash('success', 'Adhérent créé avec succès!');
    //         return $this->redirectToRoute('app_adherent');
    //     }

    //     return $this->render('adherent/create.html.twig', [
    //         'form' => $form->createView(),
    //     ]);
    // }

    // Modifier un adhérent existant
    #[Route('/adherent/{id}/edit', name: 'adherent_edit')]
    public function edit(Request $request, Adherent $adherent, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AdherentType::class, $adherent); // Formulaire de modification
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush(); // Enregistrer les modifications
            $this->addFlash('success', 'Adhérent modifié avec succès!');
            return $this->redirectToRoute('adherent_show', ['id' => $adherent->getId()]);
        }

        return $this->render('adherent/edit.html.twig', [
            'form' => $form->createView(),
            'adherent' => $adherent,
        ]);
    }

    // Supprimer un adhérent
    #[Route('/adherent/{id}/delete', name: 'adherent_delete')]
    public function delete(Request $request, Adherent $adherent, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $adherent->getId(), $request->request->get('_token'))) {
            $entityManager->remove($adherent);
            $entityManager->flush();
            $this->addFlash('success', 'Adhérent supprimé avec succès!');
        }

        return $this->redirectToRoute('app_adherent');
    }
}

templates/adherent/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription d'un Adhérent
{% endblock %}

{% block body %}
	<h1>Inscription d'un nouvel adhérent</h1>

	{{ form_start(form) }}
	{{ form_widget(form) }}
	<button type="submit" class="btn btn-success">S'inscrire</button>
	{{ form_end(form) }}

	<a href="{{ path('app_adherent') }}" class="btn btn-secondary mt-3">Retour à la liste</a>
{% endblock %}

templates/adherent/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'Adhérent
{% endblock %}

{% block body %}
	<h1>Modifier l'adhérent
		{{ adherent.nom }}
		{{ adherent.prenom }}</h1>

	{{ form_start(form) }}
	{{ form_widget(form) }}
	<button type="submit" class="btn btn-warning">Mettre à jour</button>
	{{ form_end(form) }}

	<a href="{{ path('adherent_show', {'id': adherent.id}) }}" class="btn btn-secondary mt-3">Retour à l'adhérent</a>
{% endblock %}

templates/adherent/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Adhérents
{% endblock %}
{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>

	<div class="example-wrapper">
		<h1>Liste des Adhérents</h1>

		{# This friendly message is coming from:
					<ul>
						<li>Your controller at
							<code>/app/src/Controller/AdherentController.php</code>
						</li>
						<li>Your template at
							<code>/app/templates/adherent/index.html.twig</code>
						</li>
					</ul> #}
	</div>
	<a href="{{ path('inscription_adherent') }}" class="btn btn-primary mb-3">Ajouter un Adhérent</a>

	{% if app.session.flashbag.has('success') %}
		<div class="alert alert-success">
			{% for message in app.session.flashbag.get('success') %}
				<p>{{ message }}</p>
			{% endfor %}
		</div>
	{% endif %}

	<table class="table">
		<thead>
			<tr>
				<th>Nom</th>
				<th>Prénom</th>
				<th>Email</th>
				<th>Date d'inscription</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for adherent in adherents %}
				<tr>
					<td>{{ adherent.nom }}</td>
					<td>{{ adherent.prenom }}</td>
					<td>{{ adherent.email }}</td>
					<td>{{ adherent.dateInscription|date('d/m/Y') }}</td>
					<td>
						<a href="{{ path('adherent_show', {'id': adherent.id}) }}" class="btn btn-info btn-sm">Voir</a>
						<a href="{{ path('adherent_edit', {'id': adherent.id}) }}" class="btn btn-warning btn-sm">Modifier</a>
						<form action="{{ path('adherent_delete', {'id': adherent.id}) }}" method="post" style="display:inline;" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet adhérent ?');">
							<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adherent.id) }}">
							<button type="submit" class="btn btn-danger btn-sm">Supprimer</button>
						</form>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="5" class="text-center">Aucun adhérent trouvé.</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/adherent/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails de l'Adhérent
{% endblock %}

{% block body %}
	<h1>Détails de l'adhérent
		{{ adherent.nom }}
		{{ adherent.prenom }}</h1>

	<ul>
		<li>
			<strong>Nom :</strong>
			{{ adherent.nom }}</li>
		<li>
			<strong>Prénom :</strong>
			{{ adherent.prenom }}</li>
		<li>
			<strong>Email :</strong>
			{{ adherent.email }}</li>
		<li>
			<strong>Téléphone :</strong>
			{{ adherent.telephone }}</li>
		<li>
			<strong>Date de naissance :</strong>
			{{ adherent.dateDeNaissance ? adherent.dateDeNaissance|date('d/m/Y') : 'Non spécifiée' }}</li>
		<li>
			<strong>Date d'inscription :</strong>
			{{ adherent.dateInscription|date('d/m/Y') }}</li>
		<li>
			<strong>Date d'expiration de la licence :</strong>
			{{ adherent.dateExpirationLicence|date('d/m/Y') }}</li>
		<li>
			<strong>Niveau :</strong>
			{{ adherent.niveau }}</li>
		<li>
			<strong>Rôle :</strong>
			{{ adherent.roleAdherent }}</li>
	</ul>

	<a href="{{ path('adherent_edit', {'id': adherent.id}) }}" class="btn btn-warning">Modifier</a>
	<a href="{{ path('app_adherent') }}" class="btn btn-secondary">Retour à la liste</a>
{% endblock %}